name: executando_sons
description: A new Flutter project.

androidX: true

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  audioplayers: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/imagens/executar.png
    - assets/imagens/parar.png
    - assets/imagens/pausar.png

    - assets/audios/bach.mp3
    - assets/audios/musica.mp3
    - assets/audios/audio.mp3